services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./data:/code/data
    restart: always
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - SECRET_KEY=${SECRET_KEY}
